---
title: Updates

format: 
  html: 
    page-layout: full
    css:
      - ../assets/listing-default.css
      - ../assets/updates.css
title-block-banner: false
---

- [First beta version of `debiasR` now available](2026-06-14-debiasr-beta-launch/)
  - June 12, 2026

- [DEBIAS at Mobile Tartu](2026-06-07-mobile-tartu/)
  - June 7, 2026

- [Visit to Boston: Northeastern University, MIT Senseable City Lab and UrbanNET](2026-06-02-boston-visit-urbannet/)
  - June 2, 2026

- [Joining the UN Committee of Experts on Big Data and Data Science for Official Statistics](2026-04-28-un-cebd-mobile-phone-data/)
  - April 28, 2026

- [Digital trace data for the study of urban dynamics: a valuable asset with caveats](2026-03-19-city-lab-barcelona/)
  - March 19, 2026

- [Keynote at the Winter Workshop on Complex Systems](2026-01-29-winter-workshop-complex-systems/)
  - January 29, 2026

- [Invited lectures at CEMFI on spatial analysis](2025-09-13-cemfi-spatial-analysis/)
  - September 13, 2025

- [Contribution to workshop at the Complexity Science Hub](2025-05-04-complexity-science-hub/)
  - May 4, 2025

- [Keynote at CompleNet 2025, Fortaleza, Brazil](2025-04-25-complenet/)
  - April 25, 2025

- [Lecture at the Erasmus Mundus MSc in Geospatial Technologies program](2025-01-23-erasmus-mundus-geospatial-technologies/)
  - January 23, 2025

- [DEBIAS joins the Collaborative Group on Nowcasting Populations](2025-01-15-nowcasting-populations/)
  - January 15, 2025
