#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(scholar)
  library(dplyr)
  library(purrr)
  library(stringr)
})

scholar_id <- "qAvR9zgAAAAJ"
out_file <- "publication/_scholar_publications.md"

format_initials <- function(x) {
  tokens <- str_split(str_squish(x), "\\s+")[[1]]
  initials <- vapply(tokens, function(tok) {
    letter <- str_match(tok, "([A-Za-zÀ-ÖØ-öø-ÿ])")[, 2]
    ifelse(is.na(letter), "", toupper(letter))
  }, character(1))
  initials <- initials[initials != ""]
  paste0(initials, ".", collapse = " ")
}

format_author <- function(author_token) {
  parts <- str_split(str_squish(author_token), "\\s+")[[1]]
  if (length(parts) < 2) return(author_token)
  family <- parts[length(parts)]
  given <- paste(parts[-length(parts)], collapse = " ")
  paste0(family, ", ", format_initials(given))
}

format_authors_apa <- function(author_string) {
  authors <- str_split(author_string, ",\\s*")[[1]] |> str_squish()
  authors <- authors[authors != ""]
  if (length(authors) == 0) return("")
  formatted <- vapply(authors, format_author, character(1))
  if (length(formatted) == 1) return(formatted)
  if (length(formatted) == 2) return(paste(formatted, collapse = " & "))
  paste0(paste(formatted[-length(formatted)], collapse = ", "), ", & ", formatted[length(formatted)])
}

escape_md_text <- function(x) {
  x |>
    str_replace_all("\\[", "\\\\[") |>
    str_replace_all("\\]", "\\\\]")
}

extract_year <- function(date_str, fallback_year = NA_integer_) {
  if (!is.na(date_str) && date_str != "") {
    y <- suppressWarnings(as.integer(str_sub(date_str, 1, 4)))
    if (!is.na(y)) return(y)
  }
  fallback_year
}

parse_sort_date <- function(date_str, fallback_year = NA_integer_) {
  if (!is.na(date_str) && date_str != "") {
    d <- suppressWarnings(as.Date(date_str, format = "%Y/%m/%d"))
    if (!is.na(d)) return(d)
  }
  if (!is.na(fallback_year)) return(as.Date(sprintf("%04d-01-01", fallback_year)))
  as.Date("1900-01-01")
}

build_fallback_scholar_url <- function(pubid) {
  paste0(
    "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=",
    scholar_id,
    "&citation_for_view=",
    scholar_id,
    ":",
    pubid
  )
}

raw_pubs <- get_publications(scholar_id)

if (!is.data.frame(raw_pubs)) {
  stop(
    paste(
      "Failed to fetch publications from Google Scholar.",
      "The request was likely rate-limited.",
      "Try again later or restore publication/_scholar_publications.md from git history."
    ),
    call. = FALSE
  )
}

pubs <- raw_pubs |>
  mutate(
    year_raw = suppressWarnings(as.integer(year)),
    authors_full = map2_chr(pubid, author, function(id, author_fallback) {
      x <- tryCatch(get_complete_authors(scholar_id, id, initials = FALSE), error = function(e) NA_character_)
      ifelse(is.na(x) || x == "", author_fallback, x)
    }),
    pub_date = map_chr(pubid, function(id) {
      x <- tryCatch(get_publication_date(scholar_id, id), error = function(e) NA_character_)
      ifelse(is.na(x) || x == "", NA_character_, x)
    }),
    year = map2_int(pub_date, year_raw, extract_year),
    sort_date = as.Date(vapply(seq_along(pubid), function(i) {
      parse_sort_date(pub_date[i], year[i])
    }, as.Date("1970-01-01")), origin = "1970-01-01"),
    direct_url = map_chr(pubid, function(id) {
      url <- tryCatch(get_publication_url(scholar_id, id), error = function(e) NA_character_)
      ifelse(is.na(url) || url == "", build_fallback_scholar_url(id), url)
    }),
    authors_apa = vapply(authors_full, format_authors_apa, character(1)),
    title_md = paste0("[", escape_md_text(title), "](", direct_url, ")"),
    journal_clean = str_squish(coalesce(journal, "")),
    number_clean = str_squish(coalesce(number, "")),
    venue = case_when(
      journal_clean != "" & number_clean != "" ~ paste0("*", journal_clean, "*, ", number_clean),
      journal_clean != "" ~ paste0("*", journal_clean, "*"),
      TRUE ~ ""
    ),
    citation = case_when(
      venue != "" ~ paste0(authors_apa, " (", year, "). ", title_md, ". ", venue, "."),
      TRUE ~ paste0(authors_apa, " (", year, "). ", title_md, ".")
    )
  ) |>
  arrange(desc(sort_date), desc(year), title)

header <- c(
  "<!-- This file is auto-generated by scripts/update_publications_from_scholar.R -->",
  "",
  paste0("Last update from: ", Sys.Date()),
  ""
)

lines <- c(
  header,
  paste0("- ", pubs$citation)
)

writeLines(lines, out_file)
cat("Wrote", nrow(pubs), "publications to", out_file, "\n")
