#!/usr/bin/env Rscript

extract_front_matter <- function(lines) {
  if (length(lines) < 3 || trimws(lines[1]) != "---") return(character(0))
  end_idx <- which(trimws(lines[-1]) == "---")
  if (!length(end_idx)) return(character(0))
  lines[2:end_idx[1]]
}

extract_field <- function(fm, key) {
  pat <- paste0("^", key, ":\\s*(.*)$")
  hit <- grep(pat, fm, value = TRUE)
  if (!length(hit)) return(NA_character_)
  val <- sub(pat, "\\1", hit[1])
  val <- gsub('^"|"$', "", trimws(val))
  if (!nzchar(val)) return(NA_character_)
  val
}

extract_authors <- function(fm) {
  a_idx <- grep("^author:\\s*$", fm)
  if (!length(a_idx)) return(character(0))
  i <- a_idx[1] + 1
  out <- character(0)
  while (i <= length(fm) && grepl("^\\s*-\\s+", fm[i])) {
    out <- c(out, sub("^\\s*-\\s+", "", trimws(fm[i])))
    i <- i + 1
  }
  out
}

extract_url <- function(lines) {
  hit <- grep("^\\*\\*URL:\\*\\*\\s*", lines, value = TRUE)
  if (!length(hit)) return(NA_character_)
  m <- regmatches(hit[1], regexpr("https?://[^\\]\\)\\s]+", hit[1], perl = TRUE))
  if (!length(m) || is.na(m)) return(NA_character_)
  m
}

extract_description <- function(lines) {
  hit <- grep("^\\*\\*Description:\\*\\*\\s*", lines, value = TRUE)
  if (!length(hit)) return(NA_character_)
  desc <- sub("^\\*\\*Description:\\*\\*\\s*", "", hit[1])
  desc <- trimws(desc)
  # Keep first sentence for a short description.
  if (grepl("\\.\\s", desc)) desc <- sub("^(.*?\\.)(\\s.*)?$", "\\1", desc)
  desc
}

parse_date <- function(x) {
  if (is.na(x)) return(as.Date("1900-01-01"))
  x <- trimws(x)
  if (grepl("^\\d{4}-\\d{2}-\\d{2}$", x)) return(as.Date(x))
  if (grepl("^\\d{4}-\\d{2}$", x)) return(as.Date(paste0(x, "-01")))
  if (grepl("^\\d{4}$", x)) return(as.Date(paste0(x, "-01-01")))
  as.Date("1900-01-01")
}

clean_title <- function(x) {
  x <- gsub("<br\\s*/?>", " ", x, ignore.case = TRUE)
  trimws(gsub("\\s+", " ", x))
}

course_files <- list.files("courses", pattern = "index\\.qmd$", recursive = TRUE, full.names = TRUE)
course_files <- course_files[normalizePath(course_files, mustWork = FALSE) != normalizePath("courses/index.qmd", mustWork = FALSE)]

items <- lapply(course_files, function(path) {
  lines <- readLines(path, warn = FALSE, encoding = "UTF-8")
  fm <- extract_front_matter(lines)
  title <- clean_title(extract_field(fm, "title"))
  date <- extract_field(fm, "date")
  authors <- extract_authors(fm)
  url <- extract_url(lines)
  desc <- extract_description(lines)
  list(
    title = title,
    date = parse_date(date),
    authors = authors,
    url = url,
    desc = desc
  )
})

ord <- order(vapply(items, function(x) x$date, as.Date("1900-01-01")), decreasing = TRUE)
items <- items[ord]

out_lines <- c("<!-- Auto-generated by scripts/update_courses_list.R -->", "")
for (it in items) {
  title_md <- if (!is.na(it$url) && nzchar(it$url)) {
    paste0("[", it$title, "](", it$url, ")")
  } else {
    it$title
  }
  authors_txt <- if (length(it$authors)) paste(it$authors, collapse = ", ") else "N/A"
  desc_txt <- if (!is.na(it$desc) && nzchar(it$desc)) it$desc else "No description available."
  out_lines <- c(
    out_lines,
    paste0("- ", title_md),
    paste0("  - Description: ", desc_txt),
    paste0("  - Authors: ", authors_txt),
    ""
  )
}

writeLines(out_lines, "courses/_courses_list.md")
cat("Wrote", length(items), "courses to courses/_courses_list.md\n")
